<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="DBMSRules.schema.json" />
    <None Remove="OutputValueType.schema.json" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="DBMSRules.schema.json" />
    <EmbeddedResource Include="OutputValueType.schema.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.13" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.13" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.13" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.13">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Avalonia.Xaml.Behaviors" Version="11.3.0.6" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Jint" Version="4.8.0" />
    <PackageReference Include="Svg.Controls.Skia.Avalonia" Version="11.3.9.5" />
  </ItemGroup>

  <ProjectExtensions><VisualStudio><UserProperties dbmsrules_1schema_1json__JsonSchema="https://json-schema.org/draft-04/schema" /></VisualStudio></ProjectExtensions>
</Project>
